### ISSUE TITLE
Transaction Reference

### ISSUE THREAD

**Issue by strateg2016** [mrfoh/paystackcordovav2#10]
Hi bro.

Is it possible to supply a Transaction Reference Number to the options being passed? This is in a case where the Transaction Reference follows an Algorithm based on Company Policy.

Thanx

**Comment by mrfoh** [comment]
Sorry about the late response. With the Paystack Android SDK am not sure, but with the REST API I think you can.

**Comment by strateg2016** [comment]
Hi. Sorry abt the late reply. Been out of it, of sorts.

I actually meant with your plugin. Like we have this:
```
var options = {
            card_number: Fund.CardNumber,
            expiry_month: Fund.Month,
            expiry_year: "20" + Fund.Year,
            cvc: Fund.CVV,
            email: Fund.Email,
            amount: Fund.Amount * 100,
            reference: TransReference
        }
```

SO that instead of using the reference returned to us, we can use the reference we pass.

Thanx

**Comment by mrfoh** [comment]
Passing a custom transaction reference is not available in the current version of this plugin, however I plan to make it available soon.

**Comment by strateg2016** [comment]
Okay. Thanks bro.
