### ISSUE TITLE
missing exec

### ISSUE THREAD

**Issue by strateg2016** [mrfoh/paystackcordovav2#9]
Hi.

When I apply the methods in my app (eg.chargeCard):
- Using the Ripple Emulator, I get a "missing exec:PaystackCordova.chargeCard" popup error.
- Using Device Emulator (or Device itself), the method is not even fired.

![picture1](https://cloud.githubusercontent.com/assets/23718479/20594346/2964f0b0-b236-11e6-95f2-6e3fad8bf134.png)

**Comment by mrfoh** [comment]
How are you making the calls to the methods?

**Comment by strateg2016** [comment]
Just like you put it in the ReadMe file.

 ```
var options = {
            card_number: "4123450131001381",
            expiry_month: 7,
            expiry_year: 2019,
            cvc: 883,
            email: "john.doe@acme.com",
            amount: 50000
        }

        window.plugins.paystackCordova.chargeCard(options, function (response) {
            console.log(response);
            //Perform verification with response.reference
        }, function (err) {
            console.log(err);
            //Perform error handling
        });
```

**Comment by mrfoh** [comment]
Are you building your app with ionic framework? If so i can send a zip with example code to get you started.
P.S
Make sure your run `cordova build android` after installing the plugin

**Comment by strateg2016** [comment]
Yes. I am building it with the ionic framework....using Visual Studio as my development tool

**Comment by mrfoh** [comment]
check out this repo https://github.com/mrfoh/paystackv2tutorial should help

**Comment by strateg2016** [comment]
Ok. I will try it and get back to you

**Comment by strateg2016** [comment]
Problem still persists...even when I use your code/project

**Comment by mrfoh** [comment]
How are you testing? On a device or an emulator. If you could you the
chrome webview inspector to debug the app while its running on a device or
an emulator.

**Comment by strateg2016** [comment]
Ok...I seem to have gotten it working. I have been using Ripple Emulator to test, and once in a while, my device. Don't know what it is I did that got it to work...but it seems to be working.

Thanks for your help and sorry for the inconvenience.

**Comment by mrfoh** [comment]
That's great, I recommend using an emulator or a device and chrome web view
inspector to debug. It will make development easier for you.

**Comment by strateg2016** [comment]
Yeah. I guess its after I installed Crosswalk WebView that it worked.
